replicaCount: 1

image:
  repository: marksouthworth/trading212-portfolio-poller-docker-container-image
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1759002866"

imagePullSecrets: []

nameOverride: "trading212poller"
fullnameOverride: "trading212poller"

serviceAccount:
  create: true
  annotations: {}
  name: "trading212poller-sa"

podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "trading212poller"
  vault.hashicorp.com/agent-inject-secret-config: "kv/data/trading212poller/secrets"
  vault.hashicorp.com/agent-inject-template-config: |
    {{- with secret "kv/data/trading212poller/config" -}}
      export T212_API_TOKEN="{{ .Data.data.T212_API_TOKEN }}"
      export MONGO_PASSWORD="{{ .Data.data.MONGO_PASSWORD }}"
    {{- end }}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true 
  className: ""
  annotations: {}
  hosts:
    - host: trading212poller.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
