apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: trading212poller-spc
spec:
  provider: vault
  secretObjects:
    - secretName: trading212poller-secret
      type: Opaque
      data:
        - objectName: MONGO_HOST        # Must match objectName in parameters.objects
          key: MONGO_HOST
        - objectName: MONGO_PASSWORD
          key: MONGO_PASSWORD
        - objectName: MONGO_USER
          key: MONGO_USER
        - objectName: T212_API_TOKEN
          key: T212_API_TOKEN
        - objectName: T212_BASE_API_PATH
          key: T212_BASE_API_PATH
  parameters:
    roleName: trading212poller
    objects: |
      - objectName: MONGO_HOST
        secretPath: kv/data/trading212poller
        secretKey: MONGO_HOST
      - objectName: MONGO_PASSWORD
        secretPath: kv/data/trading212poller
        secretKey: MONGO_PASSWORD
      - objectName: MONGO_USER
        secretPath: kv/data/trading212poller
        secretKey: MONGO_USER
      - objectName: T212_API_TOKEN
        secretPath: kv/data/trading212poller
        secretKey: T212_API_TOKEN
      - objectName: T212_BASE_API_PATH
        secretPath: kv/data/trading212poller
        secretKey: T212_BASE_API_PATH