version: '3'
services:
  trading212poller:
    build:
      context: ../.
    ports:
      - "80:5000"
    depends_on:
      mongodb:
        condition: service_healthy
    restart: always
  mongodb:
    image: "mongo:4.4.27"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      retries: 5
      interval: 15s
      start_period: 30s
    ports:
      - "27017:27017"