name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag trading212poller:$(date +%s)

    - uses: actions/checkout@v3
    - name: Package the Helm Chart
      run: cd containerisation/helm/Trading212PortfolioPoller & ls -altr
